-- Autocmds are automatically loaded on the VeryLazy event
-- Default autocmds that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/autocmds.lua
-- Add any additional autocmds here
-- local lualine = require("lualine")
--
-- vim.api.nvim_create_autocmd({ group = "Recording", pattern = "*" }, {
--   callback = function()
--     lualine.refresh({ place = { "statusline" } })
--   end,
-- })
