return {
	"folke/which-key.nvim",
	event = "VeryLazy",
	config = function()
		local wk = require("which-key")

		wk.add({
			{ "<leader>f", group = "[F]ind", icon = "  " },
			{ "<leader>f_", hidden = true },
			{ "<leader>c", group = "[C]ode", icon = " 󰅭 " },
			{ "<leader>c_", hidden = true },
			{ "<leader>l", group = "[L]sp", icon = "  " },
			{ "<leader>l_", hidden = true },
			{ "<leader>n", group = "[N]otifications", icon = "  " },
			{ "<leader>n_", hidden = true },
			{ "<leader>g", group = "[G]oto </>", icon = "  " },
			{ "<leader>g_", hidden = true },
			{ "<leader>t", group = "[T]oggles", icon = " 󰺟 " },
			{ "<leader>t_", hidden = true },
			{ "<leader>sg", group = "[G]it", icon = "  " },
			{ "<leader>sg_", hidden = true },
			{ "<leader>o", group = "[O]bsidian", icon = " 󱓧 " },
			{ "<leader>o_", hidden = true },
			{ "<leader>T", group = "[T]abs", icon = " 󰓩 " },
			{ "<leader>T_", hidden = true },
			{ "<leader>q", group = "[Q]uit", icon = " 󰩈 " },
			{ "<leader>q_", hidden = true },
			{ "<leader>w", group = "[W]indows", icon = "  " },
			{ "<leader>w_", hidden = true },
			{ "<leader>b", group = "[B]uffers", icon = "  " },
			{ "<leader>b_", hidden = true },
			{ "<leader>x", group = "Diagnostics & Trouble", icon = " 󰨮 " },
			{ "<leader>x_", hidden = true },
			{ "<leader>L", hidden = true, group = "Lazy", icon = " 󰒲 " },
			{ "<leader>e", hidden = true },
			{ "<leader><space>", hidden = true },
			{ "<leader>/", hidden = true },
			{ "<leader>r", hidden = true },
			{ "<leader>d", hidden = true },
			{ "<leader>-", hidden = true },
		})
	end,
	opts = {
		preset = "modern",
		layout = {
			spacing = 5,
		},
		spec = {},
	},
}
